import "./globals.css";
import type { Metadata } from "next";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="sv">
      <body className="">{children}</body>
    </html>
  );
};

export default RootLayout;
export { metadata };
